//                                   _           _    __ _ _        //
//                                  | |         | |  / _(_) |       //
//    __ _  ___ _ __   ___ _ __ __ _| |_ ___  __| | | |_ _| | ___   //
//   / _` |/ _ \ '_ \ / _ \ '__/ _` | __/ _ \/ _` | |  _| | |/ _ \  //
//  | (_| |  __/ | | |  __/ | | (_| | ||  __/ (_| | | | | | |  __/  //
//   \__, |\___|_| |_|\___|_|  \__,_|\__\___|\__,_| |_| |_|_|\___|  //
//    __/ |                                                         //
//   |___/                                                          //
//                                                                  //
// Generated by:  libraries/chain_id/identify_chain.cpp             //
//                                                                  //
// Warning: This is a generated file, any changes made here will be //
// overwritten by the build process.  If you need to change what    //
// is generated here, you should use the CMake variable             //
// GRAPHENE_EGENESIS_JSON to specify an embedded genesis state.     //
//                                                                  //

/*
 * Copyright (c) 2015, Cryptonomex, Inc.
 * All rights reserved.
 *
 * This source code is provided for evaluation in private test networks only, until September 8, 2015. After this date, this license expires and
 * the code may not be used, modified or distributed for any purpose. Redistribution and use in source and binary forms, with or without modification,
 * are permitted until September 8, 2015, provided that the following conditions are met:
 *
 * 1. The code and/or derivative works are used only for private test networks consisting of no more than 10 P2P nodes.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 * ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#include <graphene/chain/protocol/types.hpp>
#include <graphene/egenesis/egenesis.hpp>

namespace graphene { namespace egenesis {

using namespace graphene::chain;

static const char genesis_json_array[161][40+1] =
{
"{\"initial_timestamp\":\"2019-02-21T19:41:0",
"0\",\"max_core_supply\":\"1000000000000000\",",
"\"initial_parameters\":{\"current_fees\":{\"p",
"arameters\":[[0,{\"fee\":2000000,\"price_per",
"_kbyte\":1000000}],[1,{\"fee\":500000}],[2,",
"{\"fee\":0}],[3,{\"fee\":2000000}],[4,{}],[5",
",{\"basic_fee\":500000,\"premium_fee\":20000",
"0000,\"price_per_kbyte\":100000}],[6,{\"fee",
"\":2000000,\"price_per_kbyte\":100000}],[7,",
"{\"fee\":300000}],[8,{\"membership_annual_f",
"ee\":200000000,\"membership_lifetime_fee\":",
"1000000000}],[9,{\"fee\":50000000}],[10,{\"",
"symbol3\":\"50000000000\",\"symbol4\":\"300000",
"00000\",\"long_symbol\":500000000,\"price_pe",
"r_kbyte\":10}],[11,{\"fee\":50000000,\"price",
"_per_kbyte\":10}],[12,{\"fee\":50000000}],[",
"13,{\"fee\":50000000}],[14,{\"fee\":2000000,",
"\"price_per_kbyte\":100000}],[15,{\"fee\":20",
"00000}],[16,{\"fee\":100000}],[17,{\"fee\":1",
"0000000}],[18,{\"fee\":50000000}],[19,{\"fe",
"e\":100000}],[20,{\"fee\":500000000}],[21,{",
"\"fee\":2000000}],[22,{\"fee\":2000000,\"pric",
"e_per_kbyte\":10}],[23,{\"fee\":2000000,\"pr",
"ice_per_kbyte\":10}],[24,{\"fee\":100000}],",
"[25,{\"fee\":100000}],[26,{\"fee\":100000}],",
"[27,{\"fee\":2000000,\"price_per_kbyte\":10}",
"],[28,{\"fee\":0}],[29,{\"fee\":500000000}],",
"[30,{\"fee\":2000000}],[31,{\"fee\":100000}]",
",[32,{\"fee\":100000}],[33,{\"fee\":2000000}",
"],[34,{\"fee\":500000000}],[35,{\"fee\":1000",
"00,\"price_per_kbyte\":10}],[36,{\"fee\":100",
"000}],[37,{}],[38,{\"fee\":2000000,\"price_",
"per_kbyte\":10}],[39,{\"fee\":500000,\"price",
"_per_output\":500000}],[40,{\"fee\":500000,",
"\"price_per_output\":500000}],[41,{\"fee\":5",
"00000}],[42,{}],[43,{\"fee\":2000000}],[44",
",{}]],\"scale\":10000},\"block_interval\":5,",
"\"maintenance_interval\":86400,\"maintenanc",
"e_skip_slots\":3,\"committee_proposal_revi",
"ew_period\":1209600,\"maximum_transaction_",
"size\":2048,\"maximum_block_size\":20480000",
"00,\"maximum_time_until_expiration\":86400",
",\"maximum_proposal_lifetime\":2419200,\"ma",
"ximum_asset_whitelist_authorities\":10,\"m",
"aximum_asset_feed_publishers\":10,\"maximu",
"m_witness_count\":1001,\"maximum_committee",
"_count\":1001,\"maximum_authority_membersh",
"ip\":10,\"reserve_percent_of_fee\":2000,\"ne",
"twork_percent_of_fee\":2000,\"lifetime_ref",
"errer_percent_of_fee\":3000,\"cashback_ves",
"ting_period_seconds\":31536000,\"cashback_",
"vesting_threshold\":10000000,\"count_non_m",
"ember_votes\":true,\"allow_non_member_whit",
"elists\":false,\"witness_pay_per_block\":10",
"00000,\"worker_budget_per_day\":\"500000000",
"00\",\"max_predicate_opcode\":1,\"fee_liquid",
"ation_threshold\":10000000,\"accounts_per_",
"fee_scale\":1000,\"account_fee_scale_bitsh",
"ifts\":4,\"max_authority_depth\":2,\"extensi",
"ons\":[]},\"initial_accounts\":[{\"name\":\"in",
"it0\",\"owner_key\":\"GPH6MRyAjQq8ud7hVNYcfn",
"VPJqcVpscN5So8BhtHuGYqET5GDW5CV\",\"active",
"_key\":\"GPH6MRyAjQq8ud7hVNYcfnVPJqcVpscN5",
"So8BhtHuGYqET5GDW5CV\",\"is_lifetime_membe",
"r\":true},{\"name\":\"init1\",\"owner_key\":\"GP",
"H6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuG",
"YqET5GDW5CV\",\"active_key\":\"GPH6MRyAjQq8u",
"d7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV",
"\",\"is_lifetime_member\":true},{\"name\":\"in",
"it2\",\"owner_key\":\"GPH6MRyAjQq8ud7hVNYcfn",
"VPJqcVpscN5So8BhtHuGYqET5GDW5CV\",\"active",
"_key\":\"GPH6MRyAjQq8ud7hVNYcfnVPJqcVpscN5",
"So8BhtHuGYqET5GDW5CV\",\"is_lifetime_membe",
"r\":true},{\"name\":\"init3\",\"owner_key\":\"GP",
"H6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuG",
"YqET5GDW5CV\",\"active_key\":\"GPH6MRyAjQq8u",
"d7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV",
"\",\"is_lifetime_member\":true},{\"name\":\"in",
"it4\",\"owner_key\":\"GPH6MRyAjQq8ud7hVNYcfn",
"VPJqcVpscN5So8BhtHuGYqET5GDW5CV\",\"active",
"_key\":\"GPH6MRyAjQq8ud7hVNYcfnVPJqcVpscN5",
"So8BhtHuGYqET5GDW5CV\",\"is_lifetime_membe",
"r\":true},{\"name\":\"init5\",\"owner_key\":\"GP",
"H6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuG",
"YqET5GDW5CV\",\"active_key\":\"GPH6MRyAjQq8u",
"d7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV",
"\",\"is_lifetime_member\":true},{\"name\":\"in",
"it6\",\"owner_key\":\"GPH6MRyAjQq8ud7hVNYcfn",
"VPJqcVpscN5So8BhtHuGYqET5GDW5CV\",\"active",
"_key\":\"GPH6MRyAjQq8ud7hVNYcfnVPJqcVpscN5",
"So8BhtHuGYqET5GDW5CV\",\"is_lifetime_membe",
"r\":true},{\"name\":\"init7\",\"owner_key\":\"GP",
"H6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuG",
"YqET5GDW5CV\",\"active_key\":\"GPH6MRyAjQq8u",
"d7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV",
"\",\"is_lifetime_member\":true},{\"name\":\"in",
"it8\",\"owner_key\":\"GPH6MRyAjQq8ud7hVNYcfn",
"VPJqcVpscN5So8BhtHuGYqET5GDW5CV\",\"active",
"_key\":\"GPH6MRyAjQq8ud7hVNYcfnVPJqcVpscN5",
"So8BhtHuGYqET5GDW5CV\",\"is_lifetime_membe",
"r\":true},{\"name\":\"init9\",\"owner_key\":\"GP",
"H6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuG",
"YqET5GDW5CV\",\"active_key\":\"GPH6MRyAjQq8u",
"d7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV",
"\",\"is_lifetime_member\":true},{\"name\":\"in",
"it10\",\"owner_key\":\"GPH6MRyAjQq8ud7hVNYcf",
"nVPJqcVpscN5So8BhtHuGYqET5GDW5CV\",\"activ",
"e_key\":\"GPH6MRyAjQq8ud7hVNYcfnVPJqcVpscN",
"5So8BhtHuGYqET5GDW5CV\",\"is_lifetime_memb",
"er\":true},{\"name\":\"nathan\",\"owner_key\":\"",
"GPH6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtH",
"uGYqET5GDW5CV\",\"active_key\":\"GPH6MRyAjQq",
"8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5",
"CV\",\"is_lifetime_member\":false}],\"initia",
"l_assets\":[],\"initial_balances\":[{\"owner",
"\":\"GPHFAbAx7yuxt725qSZvfwWqkdCwp9ZnUama\"",
",\"asset_symbol\":\"CORE\",\"amount\":\"1000000",
"000000000\"}],\"initial_vesting_balances\":",
"[],\"initial_active_witnesses\":11,\"initia",
"l_witness_candidates\":[{\"owner_name\":\"in",
"it0\",\"block_signing_key\":\"GPH6MRyAjQq8ud",
"7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV\"",
"},{\"owner_name\":\"init1\",\"block_signing_k",
"ey\":\"GPH6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So",
"8BhtHuGYqET5GDW5CV\"},{\"owner_name\":\"init",
"2\",\"block_signing_key\":\"GPH6MRyAjQq8ud7h",
"VNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV\"},",
"{\"owner_name\":\"init3\",\"block_signing_key",
"\":\"GPH6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8B",
"htHuGYqET5GDW5CV\"},{\"owner_name\":\"init4\"",
",\"block_signing_key\":\"GPH6MRyAjQq8ud7hVN",
"YcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV\"},{\"",
"owner_name\":\"init5\",\"block_signing_key\":",
"\"GPH6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8Bht",
"HuGYqET5GDW5CV\"},{\"owner_name\":\"init6\",\"",
"block_signing_key\":\"GPH6MRyAjQq8ud7hVNYc",
"fnVPJqcVpscN5So8BhtHuGYqET5GDW5CV\"},{\"ow",
"ner_name\":\"init7\",\"block_signing_key\":\"G",
"PH6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHu",
"GYqET5GDW5CV\"},{\"owner_name\":\"init8\",\"bl",
"ock_signing_key\":\"GPH6MRyAjQq8ud7hVNYcfn",
"VPJqcVpscN5So8BhtHuGYqET5GDW5CV\"},{\"owne",
"r_name\":\"init9\",\"block_signing_key\":\"GPH",
"6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGY",
"qET5GDW5CV\"},{\"owner_name\":\"init10\",\"blo",
"ck_signing_key\":\"GPH6MRyAjQq8ud7hVNYcfnV",
"PJqcVpscN5So8BhtHuGYqET5GDW5CV\"}],\"initi",
"al_committee_candidates\":[{\"owner_name\":",
"\"init0\"},{\"owner_name\":\"init1\"},{\"owner_",
"name\":\"init2\"},{\"owner_name\":\"init3\"},{\"",
"owner_name\":\"init4\"},{\"owner_name\":\"init",
"5\"},{\"owner_name\":\"init6\"},{\"owner_name\"",
":\"init7\"},{\"owner_name\":\"init8\"},{\"owner",
"_name\":\"init9\"},{\"owner_name\":\"init10\"}]",
",\"initial_worker_candidates\":[],\"initial",
"_chain_id\":\"aa34045518f1469a28fa4578240d",
"5f039afa9959c0b95ce3b39674efa691fb21\",\"i",
"mmutable_parameters\":{\"min_committee_mem",
"ber_count\":11,\"min_witness_count\":11,\"nu",
"m_special_accounts\":0,\"num_special_asset",
"s\":0}}"
};

chain_id_type get_egenesis_chain_id()
{
   return chain_id_type( "2de01491298e95083b6c9d409b67dd3fafcf671b998930e9598b9fd2e08213c3" );
}

void compute_egenesis_json( std::string& result )
{
   result.reserve( 6406 );
   result.resize(0);
   for( size_t i=0; i<161-1; i++ )
   {
      result.append( genesis_json_array[i], 40 );
   }
   result.append( std::string( genesis_json_array[ 161-1 ] ) );
   return;
}

fc::sha256 get_egenesis_json_hash()
{
   return fc::sha256( "2de01491298e95083b6c9d409b67dd3fafcf671b998930e9598b9fd2e08213c3" );
}

} }
